name: 🛠️ User Story Technique
description: Tâche technique ou architecturale
title: "[TECH STORY] "
labels: ["story", "technical"]
body:
  - type: input
    id: objectif
    attributes:
      label: Objectif technique
      placeholder: Implémenter un service de génération de jetons CSRF
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Pourquoi ?
      placeholder: |
        - Nécessaire pour sécuriser les formulaires
        - Conforme aux recommandations OWASP
  - type: textarea
    id: definition-of-done
    attributes:
      label: Définition de Done
      placeholder: |
        - Service injecté dans les contrôleurs
        - Test unitaire OK
        - PR ouverte
